server:
  port: 7000
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/mq?useUnicode=true&characterEncoding=utf-8
    username: root
    password: tp19900818
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 300000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    filters: stat,wall,log4j
    logSlowSql: true
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
mybatis:
  mapper-locations: classpath:mybatis/mapper/*Mapper.xml
  config-location: classpath:mybatis/mapper/config/sqlMapConfig.xml
  type-aliases-package: com.tp.soft
#注册中心
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
#日志
logging:
  config: logback-boot.xml
#分布式事务
tx-lcn:
  client:
    manager-address: 127.0.0.1:8070
taop:
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    database: 0
  jedis:
    pool:
      maxIdle: 10000
      maxTotal: 30000
      maxWaitMillis: 1500
      testOnBorrow: true
      testOnReturn: true
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh
keyName: tp