server:
  port: 5001

spring:
  application:
    name: tbjob-gateway
  cloud:
    gateway:
      routes:
      - id: security-route
        uri: lb://tpjob-security
        predicates:
          - Path=/tpjob-security/**
        filters:
          - name: RequestRateLimiter
            args:
              redis-rate-limiter.replenishRate: 1  # 令牌桶的容积
              redis-rate-limiter.burstCapacity: 3  # 流速 每秒
              key-resolver: "#{@remoteAddrKeyResolver}" #SPEL表达式去的对应的bean
          - StripPrefix=1
          - UserToken
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/