server:
  port: 5001

spring:
  application:
    name: tbjob-gateway
  cloud:
    gateway:
      routes:
      - id: security-route
        uri: lb://tpjob-security
        predicates:
          - Path=/tpjob-security/**
        filters:
          - StripPrefix=1
          - UserToken
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/