server:
  port: 5001
spring:
  application:
    name: tbjob-gateway
  cloud:
    gateway:
      routes:
      - id: security-route
        uri: lb://tpjob-security
        predicates:
          - Path=/tpjob-security/**
        filters:
          - name: RequestRateLimiter
            args:
              redis-rate-limiter.replenishRate: 1  # 令牌桶的容积 允许用户每秒处理多少个请求
              redis-rate-limiter.burstCapacity: 3  # 流速 每秒 允许在一秒钟内完成的最大请求数
              key-resolver: "#{@remoteAddrKeyResolver}" #SPEL表达式去的对应的bean
          - StripPrefix=1
          - UserToken
      - id: security-route
        uri: lb://tpjob-web
        predicates:
          - Path=/tpjob-web/**
  redis:
    host: 127.0.0.1
    port: 6379
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/